// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__aCYvoBaVR6HFOvTIs_EvWHuipECt9k',
    appId: '1:401389738688:web:d5e170e3165aed9b0b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    authDomain: 'login-55f41.firebaseapp.com',
    storageBucket: 'login-55f41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc363sHm0IC9k3qOh_rw9ZhTScxX_tvms',
    appId: '1:401389738688:android:9406a2e1b74adaa10b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_k7A8FhBPKFdTisA1NTbbb8OGFkBL-A',
    appId: '1:401389738688:ios:bac50a75461006410b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
    iosClientId: '401389738688-sr9rt0b54junmt6dj9m1g5lt3pc3jtah.apps.googleusercontent.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_k7A8FhBPKFdTisA1NTbbb8OGFkBL-A',
    appId: '1:401389738688:ios:42b83c44c2ebe21e0b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
    iosClientId: '401389738688-fvh1gomo50j0dj8v3m9dc1i2bh1ish5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.log.RunnerTests',
  );
}
